# Generated by Django 3.1.7 on 2021-08-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='inscricoo_istadual',
            new_name='inscricao_istadual',
        ),
    ]
