# Generated by Django 3.1.7 on 2021-06-30 09:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210628_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='Celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='DDD',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Telefone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='cep',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='cidade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='complemento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='data_de_criacao',
            field=models.DateField(blank=True, max_length=30, null=True, verbose_name='Data de criação'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='estado',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=30, verbose_name='Inscrição municipal'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='inscricoo_istadual',
            field=models.CharField(blank=True, max_length=30, verbose_name='Inscrição estadual'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='nascionalidade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='nome_fantazia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='pais',
            field=models.CharField(blank=True, max_length=10, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='plano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.plano'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='quadra',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='razao_social',
            field=models.CharField(blank=True, max_length=30, verbose_name='Razão Social'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='rua',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='setor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
