# Generated by Django 3.1.7 on 2021-08-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20210804_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='user',
        ),
    ]
