# Generated by Django 3.1.7 on 2021-06-30 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20210630_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='usuario_cliente',
        ),
    ]
