# Generated by Django 3.1.7 on 2021-11-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_plano_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('mes_referente', models.DateField(blank=True, null=True, verbose_name='Data de criação')),
                ('data_de_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de criação')),
                ('estado_do_debito', models.CharField(blank=True, max_length=50)),
                ('usuarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
    ]
