# Generated by Django 3.1.7 on 2021-06-30 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_plano_usuario_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='plano',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.plano'),
            preserve_default=False,
        ),
    ]
