# Generated by Django 3.1.7 on 2021-11-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_cobranca'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranca',
            name='link_de_cobranca',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
