# Generated by Django 3.1.7 on 2021-11-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_cobranca_link_de_cobranca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cobranca',
            old_name='Valor',
            new_name='valor',
        ),
    ]
