# Generated by Django 3.1.7 on 2021-11-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20211124_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranca',
            name='registros',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
