# Generated by Django 3.1.7 on 2022-11-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_cobranca_registros'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='registro',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
