# Generated by Django 3.1.7 on 2023-01-22 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_plano_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobranca',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='cobranca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.cobranca'),
        ),
    ]
