# Generated by Django 3.1.7 on 2023-01-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_plano_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='descricao',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
