# Generated by Django 3.1.7 on 2023-01-22 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0012_plano_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cobranca',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='usuarios.cobranca'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='plano',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='usuarios.plano'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
