# Generated by Django 3.1.7 on 2023-01-23 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_auto_20230122_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='cobranca',
        ),
        migrations.AddField(
            model_name='cobranca',
            name='usuarios',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='usuarios.usuarios'),
        ),
    ]
