# Generated by Django 3.1.7 on 2021-03-20 12:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('nome', models.CharField(blank=True, max_length=30)),
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('percentagem_de_lucro', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('valor_venda', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('valor_compra', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('entrada', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('saida', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('estoque', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('imagem', models.ImageField(blank=True, upload_to='')),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produto.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('aparti_quantidade_produto', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaMercadoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=9)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
        ),
    ]
