# Generated by Django 3.1.7 on 2022-10-20 14:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_cobranca_registros'),
        ('produto', '0002_auto_20211105_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaMercadoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=9)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('estoque_fisico_atual', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
                ('usuarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
    ]
