# Generated by Django 3.1.7 on 2021-04-03 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
        ('produto', '0002_entradamercadoria_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamercadoria',
            name='Fornecedor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.fornecedor'),
        ),
    ]
