# Generated by Django 3.1.7 on 2022-10-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_saidamercadoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaidaMercadoria',
        ),
    ]
