# Generated by Django 3.1.7 on 2021-04-21 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20210403_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocao',
            name='produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='promocao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.promocao'),
        ),
    ]
