# Generated by Django 3.1.7 on 2021-04-25 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_auto_20210421_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='valor_venda',
            new_name='desconto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='promocao',
        ),
        migrations.AddField(
            model_name='produto',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='produto',
            name='inicio_da_promocao',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_promocional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='produto',
            name='termino_da_promocao',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_vendal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.DeleteModel(
            name='Promocao',
        ),
    ]
