# Generated by Django 3.1.7 on 2021-04-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_auto_20210425_1626'),
    ]