# Generated by Django 3.1.7 on 2021-04-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_auto_20210425_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='inicio_da_promocao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='termino_da_promocao',
        ),
        migrations.AddField(
            model_name='produto',
            name='data_inicio_da_promocao',
            field=models.DateField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_termino_da_promocao',
            field=models.DateField(blank=True, default=False, null=True),
        ),
    ]
