# Generated by Django 3.1.7 on 2021-04-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_auto_20210425_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='data_inicio_da_promocao',
            new_name='data_inicio',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='data_termino_da_promocao',
            new_name='data_termino',
        ),
    ]
