# Generated by Django 3.1.7 on 2021-04-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_auto_20210425_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_inicio',
            field=models.DateField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_termino',
            field=models.DateField(default=False, null=True),
        ),
    ]
