# Generated by Django 3.1.7 on 2021-04-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_auto_20210425_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_inicio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_termino',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
