# Generated by Django 3.1.7 on 2021-04-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_auto_20210425_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, unique=True),
        ),
    ]
