# Generated by Django 3.1.7 on 2021-05-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0014_auto_20210507_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='promocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_promocional', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('data_inicio', models.DateField(blank=True, max_length=30, null=True)),
                ('data_termino', models.DateField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_termino',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='quantidade_promocional',
        ),
    ]
