# Generated by Django 3.1.7 on 2021-05-11 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0015_auto_20210511_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='promocao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produto.promocao', verbose_name='Promocao'),
            preserve_default=False,
        ),
    ]
