# Generated by Django 3.1.7 on 2021-05-11 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0016_produto_promocao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='promocao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.promocao'),
        ),
    ]
