# Generated by Django 3.1.7 on 2021-05-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0017_auto_20210511_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocao',
            name='Descricao',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
