# Generated by Django 3.1.7 on 2021-05-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0018_promocao_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocao',
            old_name='Descricao',
            new_name='descricao',
        ),
    ]
