# Generated by Django 3.1.7 on 2021-05-14 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0019_auto_20210511_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradamercadoria',
            old_name='Fornecedor',
            new_name='fornecedor',
        ),
    ]
