# Generated by Django 3.1.7 on 2021-05-14 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0009_auto_20210514_1415'),
        ('produto', '0020_auto_20210514_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamercadoria',
            name='fornecedor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.fornecedors'),
        ),
    ]
