# Generated by Django 3.1.7 on 2021-06-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0022_auto_20210514_1510'),
    ]

    operations = [

    ]
