# Generated by Django 3.1.7 on 2021-06-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0023_entradamercadoria_validade_produto'),
    ]

    operations = [

    ]
