# Generated by Django 3.1.7 on 2021-06-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0024_entradamercadoria_validade_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradamercadoria',
            name='validade_produto',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
    ]
