# Generated by Django 3.1.7 on 2021-06-21 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0025_entradamercadoria_validade_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='promocao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.promocao', verbose_name='Promoção'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='descricao',
            field=models.CharField(max_length=50, null=True, verbose_name='Descrição'),
        ),
    ]
