# Generated by Django 3.1.7 on 2021-07-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0027_auto_20210630_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='user',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='usuario_cliente',
        ),
        migrations.RemoveField(
            model_name='entradamercadoria',
            name='user',
        ),
        migrations.RemoveField(
            model_name='entradamercadoria',
            name='usuario_cliente',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='usuario_cliente',
        ),
        migrations.RemoveField(
            model_name='promocao',
            name='user',
        ),
        migrations.RemoveField(
            model_name='promocao',
            name='usuario_cliente',
        ),
    ]
