# Generated by Django 3.1.7 on 2021-07-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0030_auto_20210706_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(max_length=13),
        ),
    ]
