# Generated by Django 3.1.7 on 2021-07-20 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nascionalidade', models.CharField(blank=True, max_length=50)),
                ('cep', models.CharField(blank=True, max_length=12)),
                ('rua', models.CharField(blank=True, max_length=50)),
                ('quadra', models.CharField(blank=True, max_length=10)),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('setor', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(blank=True, max_length=10)),
                ('cidade', models.CharField(blank=True, max_length=10)),
                ('pais', models.CharField(blank=True, max_length=10, verbose_name='País')),
                ('complemento', models.CharField(blank=True, max_length=50)),
                ('Celular', models.CharField(blank=True, max_length=20)),
                ('Celular2', models.CharField(blank=True, max_length=20)),
                ('Telefone', models.CharField(blank=True, max_length=25)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoa.pessoa')),
                ('nome_fantazia', models.CharField(blank=True, max_length=50)),
                ('cnpj', models.CharField(blank=True, max_length=20)),
                ('data_de_criacao', models.DateField(blank=True, max_length=30, null=True, verbose_name='Data de criação')),
            ],
            bases=('pessoa.pessoa',),
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoa.pessoa')),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('segundo_nome', models.CharField(blank=True, max_length=50)),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('data_de_nascimento', models.DateField(blank=True, max_length=30, null=True)),
                ('sexo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoa.sexo')),
            ],
            bases=('pessoa.pessoa',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoa.pessoa')),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('segundo_nome', models.CharField(blank=True, max_length=50)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=11)),
                ('data_de_nascimento', models.DateField(blank=True, max_length=30, null=True)),
                ('sexo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoa.sexo')),
            ],
            bases=('pessoa.pessoa',),
        ),
    ]
