# Generated by Django 3.1.7 on 2021-08-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sexo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sexo',
            name='usuarios',
        ),
    ]
