# Generated by Django 3.1.7 on 2021-05-14 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_auto_20210514_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='contato',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.contato'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='endereco',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.endereco'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sexo',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.sexo'),
        ),
    ]
