# Generated by Django 3.1.7 on 2021-11-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_auto_20210928_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
