# Generated by Django 3.1.7 on 2021-05-14 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_auto_20210514_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='contato',
            new_name='contatos',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='endereco',
            new_name='enderecos',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='sexo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Celular2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Telefone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nascionalidade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='quadra',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rua',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='setor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoa.sexo'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='Celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='Celular2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='Telefone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='endereco',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='estado',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='nascionalidade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='pais',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='quadra',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='rua',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='setor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='Celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='Celular2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='Telefone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cidade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endereco',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='estado',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nascionalidade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='pais',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='quadra',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='rua',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='setor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='sexo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoa.sexo'),
        ),
    ]
