# Generated by Django 3.1.7 on 2021-05-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_auto_20210514_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='contatos',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='enderecos',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='teste',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='cidade',
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
