# Generated by Django 3.1.7 on 2021-11-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_funcionario_user_funcionario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='user',
            new_name='user_2',
        ),
    ]
