# Generated by Django 3.1.7 on 2021-11-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0006_auto_20211105_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='user_funcionario',
            new_name='user',
        ),
    ]
