# Generated by Django 3.1.7 on 2021-05-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0006_auto_20210514_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='pessoa_ptr',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='pessoa_ptr',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='pessoa_ptr',
        ),

    ]
