# Generated by Django 3.1.7 on 2021-05-14 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0007_auto_20210514_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('cnpj', models.CharField(blank=True, max_length=20)),
                ('data_de_criacao', models.CharField(blank=True, max_length=11)),
                ('endereco', models.CharField(blank=True, max_length=50)),
                ('nascionalidade', models.CharField(blank=True, max_length=50)),
                ('rua', models.CharField(blank=True, max_length=50)),
                ('quadra', models.CharField(blank=True, max_length=10)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('setor', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(blank=True, max_length=10)),
                ('cidade', models.CharField(blank=True, max_length=10)),
                ('pais', models.CharField(blank=True, max_length=10)),
                ('Celular', models.CharField(blank=True, max_length=20)),
                ('Celular2', models.CharField(blank=True, max_length=20)),
                ('Telefone', models.CharField(blank=True, max_length=25)),
                ('email', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('segundo_nome', models.CharField(blank=True, max_length=50)),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('data_de_nascimento', models.CharField(blank=True, max_length=11)),
                ('endereco', models.CharField(blank=True, max_length=50)),
                ('nascionalidade', models.CharField(blank=True, max_length=50)),
                ('rua', models.CharField(blank=True, max_length=50)),
                ('quadra', models.CharField(blank=True, max_length=10)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('setor', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(blank=True, max_length=10)),
                ('cidade', models.CharField(blank=True, max_length=10)),
                ('pais', models.CharField(blank=True, max_length=10)),
                ('Celular', models.CharField(blank=True, max_length=20)),
                ('Celular2', models.CharField(blank=True, max_length=20)),
                ('Telefone', models.CharField(blank=True, max_length=25)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('departamento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoa.departamento')),
                ('parentesco', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoa.parentesco')),
                ('sexo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoa.sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('segundo_nome', models.CharField(blank=True, max_length=50)),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('data_de_nascimento', models.CharField(blank=True, max_length=11)),
                ('endereco', models.CharField(blank=True, max_length=50)),
                ('nascionalidade', models.CharField(blank=True, max_length=50)),
                ('rua', models.CharField(blank=True, max_length=50)),
                ('quadra', models.CharField(blank=True, max_length=10)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('setor', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(blank=True, max_length=10)),
                ('cidade', models.CharField(blank=True, max_length=10)),
                ('pais', models.CharField(blank=True, max_length=10)),
                ('Celular', models.CharField(blank=True, max_length=20)),
                ('Celular2', models.CharField(blank=True, max_length=20)),
                ('Telefone', models.CharField(blank=True, max_length=25)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('sexo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoa.sexo')),
            ],
        ),
    ]
