# Generated by Django 3.1.7 on 2021-11-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0007_auto_20211105_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
