# Generated by Django 3.1.7 on 2021-11-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0008_auto_20211105_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='user_2',
        ),
    ]
