# Generated by Django 3.1.7 on 2021-05-14 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0020_auto_20210514_1415'),
        ('pessoa', '0008_auto_20210514_1345'),
    ]

    operations = [

    ]
