# Generated by Django 3.1.7 on 2021-05-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0009_auto_20210514_1415'),
    ]

    operations = [

    ]
