# Generated by Django 3.1.7 on 2021-05-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0010_auto_20210514_1431'),
    ]

    operations = [

    ]
