# Generated by Django 3.1.7 on 2021-05-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0012_auto_20210514_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionarios',
            name='parentesco',
        ),
        migrations.DeleteModel(
            name='Parentesco',
        ),
    ]
