# Generated by Django 3.1.7 on 2021-05-14 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0013_auto_20210514_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nomemm',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='nomemm',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='nomemm',
            new_name='nome_fantazia',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='teste',
            new_name='email',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_de_nascimento',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='cliente',
            name='segundo_nome',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='data_de_criacao',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_de_nascimento',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoa.departamento'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='segundo_nome',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='Celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='Celular2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='Telefone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='estado',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nascionalidade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='pais',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='quadra',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='rua',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='setor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='sexo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoa.sexo'),
        ),
    ]
