# Generated by Django 3.1.7 on 2021-05-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0014_auto_20210514_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='sexo',
        ),
    ]
