# Generated by Django 3.1.7 on 2021-05-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0015_remove_clientes_sexo'),
        ('financeiro', '0021_auto_20210514_1510'),
        ('produto', '0022_auto_20210514_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fornecedors',
        ),
        migrations.RemoveField(
            model_name='funcionarios',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='funcionarios',
            name='sexo',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Funcionarios',
        ),
    ]
