# Generated by Django 3.1.7 on 2021-05-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0016_auto_20210514_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedor',
            old_name='nome',
            new_name='nome_fantazia',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='nome_fantazia',
            new_name='nome',
        ),
    ]
