# Generated by Django 3.1.7 on 2021-05-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0017_auto_20210514_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_de_nascimento',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='data_de_criacao',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_de_nascimento',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
    ]
