# Generated by Django 3.1.7 on 2021-05-14 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0018_auto_20210514_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='sexo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoa.sexo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='sexo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoa.sexo'),
        ),
    ]
