# Generated by Django 3.1.7 on 2021-05-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0019_auto_20210514_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cpf',
            new_name='cpf_cnpj',
        ),
    ]
