# Generated by Django 3.1.7 on 2021-05-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0020_auto_20210514_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='endereco',
            new_name='complemento',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='CEP',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
