# Generated by Django 3.1.7 on 2021-05-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0021_auto_20210519_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='CEP',
            new_name='cep',
        ),
    ]
