# Generated by Django 3.1.7 on 2021-06-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0022_auto_20210519_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'permissions': [('edita CBVs ', 'pessoa.change_fornecedor')]},
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='data_de_criacao',
            field=models.DateField(blank=True, max_length=30, null=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pais',
            field=models.CharField(blank=True, max_length=10, verbose_name='País'),
        ),
    ]
