# Generated by Django 3.1.7 on 2021-06-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0023_auto_20210621_0629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'permissions': [('edita CBVs ', 'change fornecedor')]},
        ),
    ]
