# Generated by Django 3.1.7 on 2021-06-21 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0024_auto_20210621_0638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'permissions': [('edita CBVs ', 'editar fornecedor')]},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={},
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='departamento',
        ),
    ]
