# Generated by Django 3.1.7 on 2021-06-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0025_auto_20210621_0656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'permissions': [('pessoa', 'editar fornecedor')]},
        ),
    ]
