# Generated by Django 3.1.7 on 2021-06-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0026_auto_20210621_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'permissions': (('pessoa', 'editar pessoa'),)},
        ),
    ]
