# Generated by Django 3.1.7 on 2021-06-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0027_auto_20210621_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'permissions': (('editar_pessoa', 'editar pessoa'),)},
        ),
    ]
