# Generated by Django 3.1.7 on 2021-06-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0028_auto_20210621_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'permissions': (('editar_fornecedor', 'editar_fornecedor'),)},
        ),
    ]
