# Generated by Django 3.1.7 on 2021-06-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0030_auto_20210630_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='usuario_cliente',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
