# Generated by Django 3.1.7 on 2021-06-30 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20210630_1114'),
        ('pessoa', '0033_auto_20210630_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='usuario_cliente',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='usuarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
        ),
    ]
