# Generated by Django 3.1.7 on 2021-06-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20210630_1114'),
        ('pessoa', '0035_auto_20210630_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='usuarios',
            field=models.ManyToManyField(to='usuarios.Usuarios'),
        ),
    ]
