# Generated by Django 3.1.7 on 2021-03-20 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos_extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('valor', models.CharField(blank=True, max_length=14)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('arquivo', models.FileField(blank=True, default=False, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_de_conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('valor', models.CharField(blank=True, max_length=14)),
                ('parcelas', models.CharField(blank=True, max_length=14)),
                ('data_de_vencimento', models.DateField(blank=True, default=False)),
                ('arquivo', models.FileField(blank=True, default=False, upload_to='')),
                ('tipo_de_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.tipo_de_conta')),
            ],
        ),
    ]
