# Generated by Django 3.1.7 on 2023-01-25 17:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('pessoa', '0001_initial'),
        ('fluxo_de_caixa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, max_length=100, verbose_name='Observação')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('valor_com_juros', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('valor_parcela', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('parcelas_pagas', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('parcelas', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('parcelas_restantes', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('data_de_vencimento', models.DateField(blank=True, default=False)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('arquivo', models.FileField(blank=True, default=False, upload_to='')),
                ('user_2', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_de_conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelasConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_da_parcelas', models.CharField(blank=True, max_length=100, null=True)),
                ('data_de_vencimento', models.DateField(blank=True, default=False)),
                ('contas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.contas')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, max_length=100, verbose_name='Observação')),
                ('quantidade_de_parcelas', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('total_pago', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('contas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.contas')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='GastosExtrasCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome')),
                ('user', models.CharField(blank=True, max_length=30, null=True, verbose_name='Funcionário')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Gastos_extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('arquivo', models.FileField(blank=True, default=False, upload_to='')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('gastosExtrasCategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.gastosextrascategoria')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='contas',
            name='tipo_de_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.tipo_de_conta'),
        ),
        migrations.AddField(
            model_name='contas',
            name='usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='contas',
            name='venda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fluxo_de_caixa.venda'),
        ),
    ]
