# Generated by Django 3.1.7 on 2021-04-26 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0015_auto_20210425_1626'),
        ('pessoa', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelas_pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='contas',
            name='parcelas_pagas',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='contas',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa'),
        ),
        migrations.AddField(
            model_name='contas',
            name='valor_parcela',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='contas',
            name='venda',
            field=models.ForeignKey(default=376, on_delete=django.db.models.deletion.CASCADE, to='fluxo_de_caixa.venda'),
            preserve_default=False,
        ),

    ]
