# Generated by Django 3.1.7 on 2021-11-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_plano_user'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelasConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_da_parcelas', models.CharField(blank=True, max_length=100, null=True)),
                ('data_de_vencimento', models.DateField(blank=True, default=False)),
                ('contas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.contas')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
    ]
