# Generated by Django 3.1.7 on 2021-04-26 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_auto_20210426_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas',
            name='parcelas_pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financeiro.parcelas_pago'),
            preserve_default=False,
        ),
    ]
