# Generated by Django 3.1.7 on 2021-09-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_auto_20210818_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
            ],
        ),
    ]
