# Generated by Django 3.1.7 on 2021-11-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_relatorios'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastosExtrasCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, max_length=30, null=True, verbose_name='Descrição')),
            ],
        ),
    ]
