# Generated by Django 3.1.7 on 2021-04-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_contas_parcelas_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas',
            name='parcelas_restantes',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='contas',
            name='saldo_devedor',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
