# Generated by Django 3.1.7 on 2021-11-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_gastosextrascategoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gastosextrascategoria',
            old_name='Nome',
            new_name='nome',
        ),
    ]
