# Generated by Django 3.1.7 on 2021-11-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_gastos_extras_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelasconta',
            name='Juros',
        ),
        migrations.AddField(
            model_name='contas',
            name='juros',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='contas',
            name='valor_com_juros',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, null=True),
        ),
    ]
