# Generated by Django 3.1.7 on 2021-11-03 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_auto_20211103_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos_extras',
            name='gastosExtrasCategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.gastosextrascategoria'),
        ),
    ]
