# Generated by Django 3.1.7 on 2021-11-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_auto_20211112_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas',
            name='juros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='contas',
            name='valor_com_juros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
