# Generated by Django 3.1.7 on 2021-11-04 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_plano_user'),
        ('financeiro', '0007_auto_20211103_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastosextrascategoria',
            name='usuarios',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
            preserve_default=False,
        ),
    ]
