# Generated by Django 3.1.7 on 2021-11-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_auto_20211104_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos_extras',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
