# Generated by Django 3.1.7 on 2021-04-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_auto_20210426_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contas',
            name='data_de_vencimento',
        ),
    ]
