# Generated by Django 3.1.7 on 2021-11-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_auto_20211104_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas',
            name='user_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contas',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
