# Generated by Django 3.1.7 on 2021-04-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_remove_contas_data_de_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas',
            name='data_de_vencimento',
            field=models.DateField(null=True),
        ),
    ]
