# Generated by Django 3.1.7 on 2021-04-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_auto_20210426_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contas',
        ),
    ]
