# Generated by Django 3.1.7 on 2021-04-26 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0016_auto_20210426_0946'),
        ('pessoa', '0001_initial'),
        ('financeiro', '0012_delete_contas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('valor_parcela', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('parcelas_pagas', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('parcelas', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('parcelas_restantes', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('data_de_vencimento', models.DateField(blank=True, default=False)),
                ('arquivo', models.FileField(blank=True, default=False, upload_to='')),
                ('parcelas_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.parcelas_pago')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa')),
                ('tipo_de_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.tipo_de_conta')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxo_de_caixa.venda')),
            ],
        ),
    ]
