# Generated by Django 3.1.7 on 2021-04-26 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_contas'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
