# Generated by Django 3.1.7 on 2021-04-26 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
        ('financeiro', '0014_contas_data_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contas',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='contas',
            name='Cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.cliente'),
        ),
    ]
