# Generated by Django 3.1.7 on 2021-04-28 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0016_auto_20210426_0946'),
        ('financeiro', '0016_auto_20210426_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas',
            name='venda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fluxo_de_caixa.venda'),
        ),
    ]
