# Generated by Django 3.1.7 on 2021-04-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0017_auto_20210428_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contas',
            old_name='descricao',
            new_name='observacao',
        ),
    ]
