# Generated by Django 3.1.7 on 2021-05-14 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0018_auto_20210428_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contas',
            old_name='Cliente',
            new_name='cliente',
        ),
    ]
