# Generated by Django 3.1.7 on 2021-06-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0021_auto_20210514_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contas',
            name='parcelas_pago',
        ),
    ]
