# Generated by Django 3.1.7 on 2021-06-07 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0022_remove_contas_parcelas_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_de_parcelas', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('total_a_pagar', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('contas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.contas')),
            ],
        ),
        migrations.DeleteModel(
            name='Parcelas_pago',
        ),
    ]
