# Generated by Django 3.1.7 on 2021-06-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0023_auto_20210607_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='total_a_pagar',
            new_name='total_pago',
        ),
    ]
