# Generated by Django 3.1.7 on 2021-06-08 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0024_auto_20210608_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
