# Generated by Django 3.1.7 on 2021-06-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0025_pagamento_data_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='observacao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
