# Generated by Django 3.1.7 on 2021-06-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0026_pagamento_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas',
            name='observacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='gastos_extras',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='observacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Observação'),
        ),
    ]
