# Generated by Django 3.1.7 on 2021-07-01 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0006_auto_20210630_1114'),
        ('financeiro', '0027_auto_20210621_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contas',
            name='usuarios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gastos_extras',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gastos_extras',
            name='usuarios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamento',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamento',
            name='usuarios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipo_de_conta',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipo_de_conta',
            name='usuarios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
            preserve_default=False,
        ),
    ]
