# Generated by Django 3.1.7 on 2023-01-25 17:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('produto', '0001_initial'),
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_caixa', models.CharField(max_length=30)),
                ('valor_atualizado', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.funcionario')),
                ('usuarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_de_pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('valor_com_desconto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('total_desconto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('valor_recebido', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('valor_credito', models.FloatField(blank=True, default=0, null=True)),
                ('valor_cedula', models.FloatField(blank=True, default=0, null=True)),
                ('valor_debito', models.FloatField(blank=True, default=0, null=True)),
                ('troco', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('finalizada', models.CharField(blank=True, max_length=20, null=True)),
                ('nfe_emitida', models.BooleanField(default=False)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('user_2', models.CharField(blank=True, max_length=1000, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.cliente')),
                ('tipo_de_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fluxo_de_caixa.tipo_de_pagamento')),
                ('usuarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_de_itens', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('estoque_fisico_atual', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
                ('usuarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxo_de_caixa.venda')),
            ],
        ),
        migrations.CreateModel(
            name='Depositar_sacar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
                ('estado_do_caixa', models.CharField(blank=True, max_length=10, null=True, verbose_name='estado do caixa')),
                ('depositar', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('venda_realizadas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('saldo_em_caixa', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('sacar', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('caixa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fluxo_de_caixa.caixa')),
                ('usuarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
    ]
