# Generated by Django 3.1.7 on 2021-03-20 13:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0002_entradamercadoria_fornecedor'),
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_de_pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('total_desconto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('valor_recebido', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('valor_credito', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('valor_debito', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('troco', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('parcelas', models.CharField(blank=True, max_length=5)),
                ('descricao', models.CharField(blank=True, max_length=40)),
                ('pago', models.BooleanField(default=False)),
                ('nota_fiscal_emitida', models.BooleanField(blank=True, default=False)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pessoa.pessoa')),
                ('tipo_de_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fluxo_de_caixa.tipo_de_pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_de_itens', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxo_de_caixa.venda')),
            ],
        ),
    ]
