# Generated by Django 3.1.7 on 2023-01-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositar_sacar',
            old_name='estado_do_caixa',
            new_name='estadoDoCaixa',
        ),
    ]
