# Generated by Django 3.1.7 on 2023-01-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0002_auto_20230125_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositar_sacar',
            old_name='estadoDoCaixa',
            new_name='estado_do_caixa',
        ),
    ]
