# Generated by Django 3.1.7 on 2021-03-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0002_auto_20210329_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='pago',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
