# Generated by Django 3.1.7 on 2021-03-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0004_auto_20210329_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='pago',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
