# Generated by Django 3.1.7 on 2021-11-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0004_auto_20210927_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='user_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='depositar_sacar',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemdopedido',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='finalizada',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
