# Generated by Django 3.1.7 on 2022-10-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0005_auto_20211105_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdopedido',
            name='estoque_fisico_atual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9),
        ),
    ]
