# Generated by Django 3.1.7 on 2021-03-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0005_auto_20210329_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='nota_fiscal_emitida',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='pago',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
