# Generated by Django 3.1.7 on 2021-03-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0006_auto_20210329_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='nota_fiscal_emitida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venda',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
