# Generated by Django 3.1.7 on 2022-10-28 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0009_remove_pessoa_user_2'),
        ('fluxo_de_caixa', '0007_auto_20221027_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.cliente'),
        ),
    ]
