# Generated by Django 3.1.7 on 2021-03-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0007_auto_20210329_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='finalizada',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
