# Generated by Django 3.1.7 on 2022-11-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0008_auto_20221028_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdopedido',
            name='quantidade_de_itens',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9),
        ),
    ]
