# Generated by Django 3.1.7 on 2023-01-25 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0009_auto_20221108_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositar_sacar',
            name='estadoDoCaixa',
        ),
        migrations.AddField(
            model_name='caixa',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='caixa',
            name='estado_do_caixa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='estado do caixa'),
        ),
    ]
