# Generated by Django 3.1.7 on 2021-04-20 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20210403_1702'),
        ('fluxo_de_caixa', '0009_auto_20210329_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdopedido',
            name='promocao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='produto.promocao'),
            preserve_default=False,
        ),
    ]
