# Generated by Django 3.1.7 on 2023-01-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0010_auto_20230125_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='estado_do_caixa',
        ),
    ]
