# Generated by Django 3.1.7 on 2021-04-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0010_itemdopedido_promocao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdopedido',
            name='promocao',
        ),
    ]
