# Generated by Django 3.1.7 on 2023-01-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0011_remove_caixa_estado_do_caixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositar_sacar',
            name='estado_do_caixa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='estado do caixa'),
        ),
    ]
