# Generated by Django 3.1.7 on 2021-04-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0014_remove_itemdopedido_promocao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='descricao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
