# Generated by Django 3.1.7 on 2021-04-26 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
        ('fluxo_de_caixa', '0015_auto_20210425_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa'),
        ),
    ]
