# Generated by Django 3.1.7 on 2021-04-28 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0017_auto_20210428_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='tipo_de_pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fluxo_de_caixa.tipo_de_pagamento'),
        ),
    ]
