# Generated by Django 3.1.7 on 2021-04-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0018_auto_20210428_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='parcelas',
        ),
    ]
