# Generated by Django 3.1.7 on 2021-04-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0019_remove_venda_parcelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valor_credito',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_debito',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
