# Generated by Django 3.1.7 on 2021-05-14 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0020_auto_20210430_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='pessoa',
        ),
    ]
