# Generated by Django 3.1.7 on 2021-06-02 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0021_remove_venda_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_caixa', models.CharField(max_length=30)),
                ('valor_atual', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depositar_sacar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('depositar_sacar', models.CharField(max_length=30)),
                ('caixa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fluxo_de_caixa.caixa')),
            ],
        ),
    ]
