# Generated by Django 3.1.7 on 2021-06-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0022_caixa_depositar_sacar'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='valor_atualizado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
