# Generated by Django 3.1.7 on 2021-06-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0023_caixa_valor_atualizado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositar_sacar',
            old_name='depositar_sacar',
            new_name='depositar',
        ),
        migrations.AddField(
            model_name='depositar_sacar',
            name='sacar',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
