# Generated by Django 3.1.7 on 2021-06-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0024_auto_20210603_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositar_sacar',
            name='valor',
        ),
        migrations.AlterField(
            model_name='depositar_sacar',
            name='depositar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='depositar_sacar',
            name='sacar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
