# Generated by Django 3.1.7 on 2021-06-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0025_auto_20210603_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='valor_cedula',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
