# Generated by Django 3.1.7 on 2021-06-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0026_venda_valor_cedula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caixa',
            old_name='valor_atual',
            new_name='falta_depositar',
        ),
    ]
