# Generated by Django 3.1.7 on 2021-06-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0027_auto_20210607_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositar_sacar',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
