# Generated by Django 3.1.7 on 2021-06-07 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0028_depositar_sacar_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositar_sacar',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
