# Generated by Django 3.1.7 on 2021-06-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0032_auto_20210628_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='user',
        ),
        migrations.RemoveField(
            model_name='depositar_sacar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='itemdopedido',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tipo_de_pagamento',
            name='user',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='user',
        ),
    ]
