# Generated by Django 3.1.7 on 2021-06-28 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210628_1301'),
        ('fluxo_de_caixa', '0034_auto_20210628_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='usuarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='depositar_sacar',
            name='usuarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='itemdopedido',
            name='usuarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='tipo_de_pagamento',
            name='usuarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
        ),
        migrations.AddField(
            model_name='venda',
            name='usuarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
        ),
    ]
