# Generated by Django 3.1.7 on 2021-07-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0036_caixa_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositar_sacar',
            name='vendar_realizadas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
