# Generated by Django 3.1.7 on 2021-07-02 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0037_depositar_sacar_vendar_realizadas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositar_sacar',
            old_name='vendar_realizadas',
            new_name='venda_realizadas',
        ),
    ]
