# Generated by Django 3.1.7 on 2021-07-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0038_auto_20210702_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositar_sacar',
            name='valorInicialDoCaixa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
