# Generated by Django 3.1.7 on 2021-07-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0039_depositar_sacar_valorinicialdocaixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositar_sacar',
            name='AbrirFeixarCaixa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Descrição'),
        ),
    ]
