# Generated by Django 3.1.7 on 2021-07-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0040_depositar_sacar_abrirfeixarcaixa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositar_sacar',
            old_name='valorInicialDoCaixa',
            new_name='falta_depositar',
        ),
    ]
