# Generated by Django 3.1.7 on 2021-07-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0041_auto_20210702_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositar_sacar',
            old_name='AbrirFeixarCaixa',
            new_name='estadoDoCaixa',
        ),
    ]
