# Generated by Django 3.1.7 on 2021-07-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_de_caixa', '0042_auto_20210705_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositar_sacar',
            old_name='falta_depositar',
            new_name='saldo_em_caixa',
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='falta_depositar',
        ),
    ]
